import os
import pandas as pd
import numpy as np
from pathlib import Path
from requests import Request, Session
import matplotlib.pyplot as plt

data_dir = Path(__file__).resolve().parents[1] / "datasets"
data_dir.mkdir(parents=True, exist_ok=True)
results_dir = Path(__file__).resolve().parents[1] / "results"
results_dir.mkdir(exist_ok=True)

bda_path = data_dir / "BDA index.xlsx"
btc_path = data_dir / "btc price.xlsx"
fng_path = data_dir / "fng.xlsx"

fng = pd.read_excel(fng_path)
bda = pd.read_excel(bda_path)
btc = pd.read_excel(btc_path)

# Fix column names
fng = fng.rename(columns={'timestamp':'Date','value':'FNG'})
bda = bda.rename(columns={'Effective date ':'Date',
                          'S&P Cryptocurrency Broad Digital Asset Index (USD)':'BDA'})
btc = btc.rename(columns={'timestamp':'Date','value':'Bitcoin Price'})

# Convert date
fng['Date'] = pd.to_datetime(fng['Date'])
bda['Date'] = pd.to_datetime(bda['Date'])
btc['Date'] = pd.to_datetime(btc['Date'])

# Sort by date
fng = fng.sort_values('Date')
bda = bda.sort_values('Date')
btc = btc.sort_values('Date')

print("\n===== CORRELATION ANALYSIS (TRANSFORMED SERIES) =====")

# Merge all datasets on Date
merged = fng.merge(bda, on="Date", how="inner").merge(btc, on="Date", how="inner")

# Sort by date
merged = merged.sort_values("Date").reset_index(drop=True)

# Compute sentiment change (difference)
merged["FNG_diff"] = merged["FNG"].diff()

# Compute percent returns
merged["BDA_ret"] = merged["BDA"].pct_change()
merged["BTC_ret"] = merged["Bitcoin Price"].pct_change()

# Compute log returns (better for financial time series)
merged["BDA_logret"] = np.log(merged["BDA"]).diff()
merged["BTC_logret"] = np.log(merged["Bitcoin Price"]).diff()

# Drop NaNs generated by diff() and pct_change()
clean = merged.dropna()

corr_diff_bda = clean["FNG_diff"].corr(clean["BDA_logret"])
corr_diff_btc = clean["FNG_diff"].corr(clean["BTC_logret"])

corr_ret_bda = clean["FNG"].pct_change().corr(clean["BDA_logret"])
corr_ret_btc = clean["FNG"].pct_change().corr(clean["BTC_logret"])

print(f"Correlation ΔFNG vs BDA Log Returns: {corr_diff_bda:.4f}")
print(f"Correlation ΔFNG vs BTC Log Returns: {corr_diff_btc:.4f}")

print(f"Correlation FNG Returns vs BDA Log Returns: {corr_ret_bda:.4f}")
print(f"Correlation FNG Returns vs BTC Log Returns: {corr_ret_btc:.4f}")

# Rolling 30-day windows
merged["roll_corr_fng_bda"] = (
    merged["FNG_diff"]
    .rolling(window=30)
    .corr(merged["BDA_logret"])
)

merged["roll_corr_fng_btc"] = (
    merged["FNG_diff"]
    .rolling(window=30)
    .corr(merged["BTC_logret"])
)

plt.figure(figsize=(12,6))
plt.plot(merged["Date"], merged["roll_corr_fng_bda"], label="FNG vs BDA (Rolling 30d)")
plt.plot(merged["Date"], merged["roll_corr_fng_btc"], label="FNG vs BTC (Rolling 30d)")
plt.axhline(0, color="black", linewidth=1)

plt.title("Rolling 30-Day Correlation (ΔFNG vs Log Returns)")
plt.xlabel("Date")
plt.ylabel("Correlation")
plt.legend()
plt.tight_layout()
plt.savefig(results_dir / "Figure_Rolling_Correlation.png")
plt.show()

import seaborn as sns

print("\n===== GENERATING CORRELATION HEATMAP (TRANSFORMED SERIES ONLY) =====")

# Compute FNG returns
clean["FNG_return"] = clean["FNG"].pct_change()

# Select only transformed series for heatmap
corr_df = clean[[
    "FNG_diff",
    "FNG_return",
    "BDA_logret",
    "BTC_logret"
]].copy()

# Compute correlation matrix
corr_matrix = corr_df.corr()

# ---- Heatmap ----
plt.figure(figsize=(8, 6))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    linewidths=0.5,
    fmt=".2f"
)
plt.title("Correlation Heatmap (ΔFNG, FNG Returns, BDA/BTC Log Returns)")
plt.tight_layout()
plt.savefig(results_dir / "Figure_Correlation_Heatmap.png")
plt.show()

print("Saved simplified heatmap to:", results_dir / "Figure_Correlation_Heatmap.png")

# Export correlation matrix

corr_matrix.to_csv(results_dir / "correlation_matrix.csv")
corr_matrix.to_excel(results_dir / "correlation_matrix.xlsx")

print("Saved correlation matrix CSV and Excel.")

# Export individual correlation results

corr_results = pd.DataFrame({
    "Metric": [
        "Corr ΔFNG vs BDA LogRet",
        "Corr ΔFNG vs BTC LogRet",
        "Corr FNG Returns vs BDA LogRet",
        "Corr FNG Returns vs BTC LogRet"
    ],
    "Value": [
        corr_diff_bda,
        corr_diff_btc,
        corr_ret_bda,
        corr_ret_btc
    ]
})

corr_results.to_csv(results_dir / "correlation_table.csv", index=False)
corr_results.to_excel(results_dir / "correlation_table.xlsx", index=False)

print("Saved detailed correlation table CSV and Excel.")







